const String kCatchphraseAudio = 'audio/im bing bong.mp3';

const List<String> kAudioFiles = [
  'audio/definitely not.mp3',
  'audio/dont do it.mp3',
  'audio/i dunno.mp3',
  'audio/i guess so.mp3',
  'audio/i miss my wife.mp3',
  'audio/i think its fine.mp3',
  'audio/i think thats a bad idea.mp3',
  'audio/if i say yes will you take me with you_.mp3',
  'audio/if you wanna.mp3',
  'audio/im bing bong.mp3',
  'audio/im not comfortable answering that.mp3',
  'audio/im not sure.mp3',
  'audio/maybe.mp3',
  'audio/nahhh.mp3',
  'audio/no no no no no.mp3',
  'audio/no.mp3',
  'audio/noooooooooo.mp3',
  'audio/nuh uh.mp3',
  'audio/ok.mp3',
  'audio/please don_t.mp3',
  'audio/sure.mp3',
  'audio/uh yeah.mp3',
  'audio/uhhhhhh.mp3',
  'audio/yeah definitely.mp3',
  'audio/yes.mp3',
  'audio/you should ask your friends for help.mp3',
];
